-- Create currencies table
CREATE TABLE IF NOT EXISTS currencies (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  symbol TEXT NOT NULL,
  symbol_native TEXT,
  decimal_digits INTEGER DEFAULT 2,
  rounding INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT TRUE
);

-- Enable RLS
ALTER TABLE currencies ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Currencies are viewable by everyone" ON currencies
  FOR SELECT USING (true);

-- Insert currencies
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding) VALUES
('USD', 'US Dollar', '$', '$', 2, 0),
('CAD', 'Canadian Dollar', 'CA$', '$', 2, 0),
('EUR', 'Euro', '€', '€', 2, 0),
('AED', 'United Arab Emirates Dirham', 'AED', 'د.إ.‏', 2, 0),
('AFN', 'Afghan Afghani', 'Af', '؋', 0, 0),
('ALL', 'Albanian Lek', 'ALL', 'Lek', 0, 0),
('AMD', 'Armenian Dram', 'AMD', 'դր.', 0, 0),
('ARS', 'Argentine Peso', 'AR$', '$', 2, 0),
('AUD', 'Australian Dollar', 'AU$', '$', 2, 0),
('AZN', 'Azerbaijani Manat', 'man.', 'ман.', 2, 0),
('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 'KM', 2, 0),
('BDT', 'Bangladeshi Taka', 'Tk', '৳', 2, 0),
('BGN', 'Bulgarian Lev', 'BGN', 'лв.', 2, 0),
('BHD', 'Bahraini Dinar', 'BD', 'د.ب.‏', 3, 0),
('BIF', 'Burundian Franc', 'FBu', 'FBu', 0, 0),
('BND', 'Brunei Dollar', 'BN$', '$', 2, 0),
('BOB', 'Bolivian Boliviano', 'Bs', 'Bs', 2, 0),
('BRL', 'Brazilian Real', 'R$', 'R$', 2, 0),
('BWP', 'Botswanan Pula', 'BWP', 'P', 2, 0),
('BYN', 'Belarusian Ruble', 'Br', 'руб.', 2, 0),
('BZD', 'Belize Dollar', 'BZ$', '$', 2, 0),
('CDF', 'Congolese Franc', 'CDF', 'FrCD', 2, 0),
('CHF', 'Swiss Franc', 'CHF', 'CHF', 2, 0),
('CLP', 'Chilean Peso', 'CL$', '$', 0, 0),
('CNY', 'Chinese Yuan', 'CN¥', 'CN¥', 2, 0),
('COP', 'Colombian Peso', 'CO$', '$', 0, 0),
('CRC', 'Costa Rican Colón', '₡', '₡', 0, 0),
('CVE', 'Cape Verdean Escudo', 'CV$', 'CV$', 2, 0),
('CZK', 'Czech Republic Koruna', 'Kč', 'Kč', 2, 0),
('DJF', 'Djiboutian Franc', 'Fdj', 'Fdj', 0, 0),
('DKK', 'Danish Krone', 'Dkr', 'kr', 2, 0),
('DOP', 'Dominican Peso', 'RD$', 'RD$', 2, 0),
('DZD', 'Algerian Dinar', 'DA', 'د.ج.‏', 2, 0),
('EEK', 'Estonian Kroon', 'Ekr', 'kr', 2, 0),
('EGP', 'Egyptian Pound', 'EGP', 'ج.م.‏', 2, 0),
('ERN', 'Eritrean Nakfa', 'Nfk', 'Nfk', 2, 0),
('ETB', 'Ethiopian Birr', 'Br', 'Br', 2, 0),
('GBP', 'British Pound Sterling', '£', '£', 2, 0),
('GEL', 'Georgian Lari', 'GEL', 'GEL', 2, 0),
('GHS', 'Ghanaian Cedi', 'GH¢', 'GH¢', 2, 0),
('GNF', 'Guinean Franc', 'FG', 'FG', 0, 0),
('GTQ', 'Guatemalan Quetzal', 'GTQ', 'Q', 2, 0),
('HKD', 'Hong Kong Dollar', 'HK$', '$', 2, 0),
('HNL', 'Honduran Lempira', 'HNL', 'L', 2, 0),
('HRK', 'Croatian Kuna', 'kn', 'kn', 2, 0),
('HUF', 'Hungarian Forint', 'Ft', 'Ft', 0, 0),
('IDR', 'Indonesian Rupiah', 'Rp', 'Rp', 0, 0),
('ILS', 'Israeli New Sheqel', '₪', '₪', 2, 0),
('INR', 'Indian Rupee', 'Rs', '₹', 2, 0),
('IQD', 'Iraqi Dinar', 'IQD', 'د.ع.‏', 0, 0),
('IRR', 'Iranian Rial', 'IRR', '﷼', 0, 0),
('ISK', 'Icelandic Króna', 'Ikr', 'kr', 0, 0),
('JMD', 'Jamaican Dollar', 'J$', '$', 2, 0),
('JOD', 'Jordanian Dinar', 'JD', 'د.أ.‏', 3, 0),
('JPY', 'Japanese Yen', '¥', '￥', 0, 0),
('KES', 'Kenyan Shilling', 'Ksh', 'Ksh', 2, 0),
('KHR', 'Cambodian Riel', 'KHR', '៛', 2, 0),
('KMF', 'Comorian Franc', 'CF', 'FC', 0, 0),
('KRW', 'South Korean Won', '₩', '₩', 0, 0),
('KWD', 'Kuwaiti Dinar', 'KD', 'د.ك.‏', 3, 0),
('KZT', 'Kazakhstani Tenge', 'KZT', 'тңг.', 2, 0),
('LBP', 'Lebanese Pound', 'LB£', 'ل.ل.‏', 0, 0),
('LKR', 'Sri Lankan Rupee', 'SLRs', 'SL Re', 2, 0),
('LTL', 'Lithuanian Litas', 'Lt', 'Lt', 2, 0),
('LVL', 'Latvian Lats', 'Ls', 'Ls', 2, 0),
('LYD', 'Libyan Dinar', 'LD', 'د.ل.‏', 3, 0),
('MAD', 'Moroccan Dirham', 'MAD', 'د.م.‏', 2, 0),
('MDL', 'Moldovan Leu', 'MDL', 'MDL', 2, 0),
('MGA', 'Malagasy Ariary', 'MGA', 'MGA', 0, 0),
('MKD', 'Macedonian Denar', 'MKD', 'MKD', 2, 0),
('MMK', 'Myanma Kyat', 'MMK', 'K', 0, 0),
('MOP', 'Macanese Pataca', 'MOP$', 'MOP$', 2, 0),
('MUR', 'Mauritian Rupee', 'MURs', 'MURs', 0, 0),
('MXN', 'Mexican Peso', 'MX$', '$', 2, 0),
('MYR', 'Malaysian Ringgit', 'RM', 'RM', 2, 0),
('MZN', 'Mozambican Metical', 'MTn', 'MTn', 2, 0),
('NAD', 'Namibian Dollar', 'N$', 'N$', 2, 0),
('NGN', 'Nigerian Naira', '₦', '₦', 2, 0),
('NIO', 'Nicaraguan Córdoba', 'C$', 'C$', 2, 0),
('NOK', 'Norwegian Krone', 'Nkr', 'kr', 2, 0),
('NPR', 'Nepalese Rupee', 'NPRs', 'नेरू', 2, 0),
('NZD', 'New Zealand Dollar', 'NZ$', '$', 2, 0),
('OMR', 'Omani Rial', 'OMR', 'ر.ع.‏', 3, 0),
('PAB', 'Panamanian Balboa', 'B/.', 'B/.', 2, 0),
('PEN', 'Peruvian Nuevo Sol', 'S/.', 'S/.', 2, 0),
('PHP', 'Philippine Peso', '₱', '₱', 2, 0),
('PKR', 'Pakistani Rupee', 'PKRs', '₨', 0, 0),
('PLN', 'Polish Zloty', 'zł', 'zł', 2, 0),
('PYG', 'Paraguayan Guarani', '₲', '₲', 0, 0),
('QAR', 'Qatari Rial', 'QR', 'ر.ق.‏', 2, 0),
('RON', 'Romanian Leu', 'RON', 'RON', 2, 0),
('RSD', 'Serbian Dinar', 'din.', 'дин.', 0, 0),
('RUB', 'Russian Ruble', 'RUB', '₽', 2, 0),
('RWF', 'Rwandan Franc', 'RWF', 'FR', 0, 0),
('SAR', 'Saudi Riyal', 'SR', 'ر.س.‏', 2, 0),
('SDG', 'Sudanese Pound', 'SDG', 'SDG', 2, 0),
('SEK', 'Swedish Krona', 'Skr', 'kr', 2, 0),
('SGD', 'Singapore Dollar', 'S$', '$', 2, 0),
('SOS', 'Somali Shilling', 'Ssh', 'Ssh', 0, 0),
('SYP', 'Syrian Pound', 'SY£', 'ل.س.‏', 0, 0),
('THB', 'Thai Baht', '฿', '฿', 2, 0),
('TND', 'Tunisian Dinar', 'DT', 'د.ت.‏', 3, 0),
('TOP', 'Tongan Paʻanga', 'T$', 'T$', 2, 0),
('TRY', 'Turkish Lira', 'TL', 'TL', 2, 0),
('TTD', 'Trinidad and Tobago Dollar', 'TT$', '$', 2, 0),
('TWD', 'New Taiwan Dollar', 'NT$', 'NT$', 0, 0),
('TZS', 'Tanzanian Shilling', 'TSh', 'TSh', 0, 0),
('UAH', 'Ukrainian Hryvnia', '₴', '₴', 2, 0),
('UGX', 'Ugandan Shilling', 'USh', 'USh', 0, 0),
('UYU', 'Uruguayan Peso', '$U', '$', 2, 0),
('UZS', 'Uzbekistan Som', 'UZS', 'UZS', 0, 0),
('VEF', 'Venezuelan Bolívar', 'Bs.F.', 'Bs.F.', 2, 0),
('VND', 'Vietnamese Dong', '₫', '₫', 0, 0),
('XAF', 'CFA Franc BEAC', 'FCFA', 'FCFA', 0, 0),
('XOF', 'CFA Franc BCEAO', 'CFA', 'CFA', 0, 0),
('YER', 'Yemeni Rial', 'YR', 'ر.ي.‏', 0, 0),
('ZAR', 'South African Rand', 'R', 'R', 2, 0),
('ZMK', 'Zambian Kwacha', 'ZK', 'ZK', 0, 0),
('ZWL', 'Zimbabwean Dollar', 'ZWL$', '$', 2, 0)
ON CONFLICT (code) DO NOTHING;
